# Generated by Django 5.1.7 on 2025-04-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpaApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('current_status', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('date_matched', models.DateTimeField(blank=True, null=True)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('date_realized', models.DateTimeField(blank=True, null=True)),
                ('experience_end_date', models.DateField(blank=True, max_length=255, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profile_photo', models.URLField(blank=True, null=True)),
                ('home_lc_name', models.CharField(blank=True, max_length=255, null=True)),
                ('home_mc_name', models.CharField(blank=True, max_length=255, null=True)),
                ('opportunity_title', models.CharField(blank=True, max_length=255, null=True)),
                ('opportunity_duration', models.CharField(blank=True, max_length=255, null=True)),
                ('opportunity_earliest_start_date', models.DateField(blank=True, null=True)),
                ('opportunity_latest_end_date', models.DateField(blank=True, null=True)),
                ('programme_short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('programme_id', models.CharField(blank=True, max_length=255, null=True)),
                ('home_lc_name_opportunity', models.CharField(blank=True, max_length=255, null=True)),
                ('home_mc_name_opportunity', models.CharField(blank=True, max_length=255, null=True)),
                ('host_lc_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'expa_data_application',
            },
        ),
        migrations.CreateModel(
            name='SignupPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(max_length=255, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('profile_photo', models.URLField(blank=True, null=True)),
                ('home_lc_name', models.CharField(blank=True, max_length=255, null=True)),
                ('home_mc_name', models.CharField(blank=True, max_length=255, null=True)),
                ('selected_programmes', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'expa_data_signup_person',
            },
        ),
    ]
