# Generated by Django 5.1.7 on 2025-04-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expa_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expaapplication',
            name='experience_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
