# Generated by Django 5.1.7 on 2025-04-09 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expa_data', '0002_alter_expaapplication_experience_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expaapplication',
            old_name='application_id',
            new_name='ep_id',
        ),
        migrations.RenameField(
            model_name='signupperson',
            old_name='person_id',
            new_name='ep_id',
        ),
    ]
