# Generated by Django 4.2.1 on 2025-04-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expa_data', '0004_expaapplication_signuped_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expa_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('date_opened', models.DateTimeField(blank=True, null=True)),
                ('applicants_count', models.IntegerField(default=0)),
                ('accepted_count', models.IntegerField(default=0)),
                ('programme_short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sdg_target_id', models.CharField(blank=True, max_length=20, null=True)),
                ('slots', models.JSONField(blank=True, null=True)),
                ('available_slots', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
