# Generated by Django 4.2.1 on 2025-04-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expa_data', '0005_opportunity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='available_slots',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='available_slots_count',
            field=models.IntegerField(default=0),
        ),
    ]
